## import all ML + DA Library

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import sklearn as sk

## loading data file

## Data Understanding

| Column        | Description                                          |
| ------------- | ---------------------------------------------------- |
| `survived`    | Survival status (0 = No, 1 = Yes)                    |
| `pclass`      | Passenger class (1 = First, 2 = Second, 3 = Third)   |
| `sex`         | Gender of the passenger                              |
| `age`         | Age in years                                         |
| `sibsp`       | Number of siblings/spouses aboard                    |
| `parch`       | Number of parents/children aboard                    |
| `fare`        | Ticket fare paid                                     |
| `embarked`    | Port of embarkation (`C`, `Q`, `S`)                  |
| `class`       | Passenger class as text (`First`, `Second`, `Third`) |
| `who`         | Passenger category (`man`, `woman`, `child`)         |
| `adult_male`  | Whether passenger is an adult male (`True`/`False`)  |
| `deck`        | Cabin deck (`A`–`G`)                                 |
| `embark_town` | Full name of embarkation town                        |
| `alive`       | Survival status as text (`yes`, `no`)                |
| `alone`       | Whether passenger traveled alone (`True`/`False`)    |

In [17]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## check data

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [5]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [6]:
df.age.describe().round(2)

count    714.00
mean      29.70
std       14.53
min        0.42
25%       20.12
50%       28.00
75%       38.00
max       80.00
Name: age, dtype: float64

In [10]:
df.age =  df.age.fillna(np.floor(df.age.mean()))

In [14]:
df.describe().round(2)

       survived  pclass     age   sibsp   parch    fare
count    891.00  891.00  891.00  891.00  891.00  891.00
mean       0.38    2.31   29.56    0.52    0.38   32.20
std        0.49    0.84   13.01    1.10    0.81   49.69
min        0.00    1.00    0.42    0.00    0.00    0.00
25%        0.00    2.00   22.00    0.00    0.00    7.91
50%        0.00    3.00   29.00    0.00    0.00   14.45
75%        1.00    3.00   35.00    1.00    0.00   31.00
max        1.00    3.00   80.00    8.00    6.00  512.33

In [13]:
print(df.sample(10))

     survived  pclass     sex   age  sibsp  parch      fare embarked   class  \
447         1       1    male  34.0      0      0   26.5500        S   First
537         1       1  female  30.0      0      0  106.4250        C   First
195         1       1  female  58.0      0      0  146.5208        C   First
130         0       3    male  33.0      0      0    7.8958        C   Third
646         0       3    male  19.0      0      0    7.8958        S   Third
53          1       2  female  29.0      1      0   26.0000        S  Second
302         0       3    male  19.0      0      0    0.0000        S   Third
464         0       3    male  29.0      0      0    8.0500        S   Third
535         1       2  female   7.0      0      2   26.2500        S  Second
872         0       1    male  33.0      0      0    5.0000        S   First

       who  adult_male deck  embark_town alive  alone
447    man        True  NaN  Southampton   yes   True
537  woman       False  NaN    Cherbourg   yes   True
195  woman       False    B    Cherbourg   yes   True
130    man        True  NaN    Cherbourg    no   True
646    man        True  NaN  Southampton    no   True
53   woman       False  NaN  Southampton   yes  False
302    man        True  NaN  Southampton    no   True
464    man        True  NaN  Southampton    no   True
535  child       False  NaN  Southampton   yes  False
872    man        True    B  Southampton    no   True

In [9]:
print(pd.cut(df['fare'], bins=5).value_counts().sort_index())

fare
(-0.512, 102.466]     838
(102.466, 204.932]     33
(204.932, 307.398]     17
(307.398, 409.863]      0
(409.863, 512.329]      3
Name: count, dtype: int64