In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import sklearn as sk

In [2]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [25]:
numerical_features = df.select_dtypes(include=[np.number])

In [ ]:
df.select_dtypes(["float64",'int64'])
df.select_dtypes("number")
df.select_dtypes("object")

        sex embarked    who  embark_town alive
0      male        S    man  Southampton    no
1    female        C  woman    Cherbourg   yes
2    female        S  woman  Southampton   yes
3    female        S  woman  Southampton   yes
4      male        S    man  Southampton    no
..      ...      ...    ...          ...   ...
886    male        S    man  Southampton    no
887  female        S  woman  Southampton   yes
888  female        S  woman  Southampton    no
889    male        C    man    Cherbourg   yes
890    male        Q    man   Queenstown    no

[891 rows x 5 columns]

In [26]:
numerical_features

     survived  pclass   age  sibsp  parch     fare
0           0       3  22.0      1      0   7.2500
1           1       1  38.0      1      0  71.2833
2           1       3  26.0      0      0   7.9250
3           1       1  35.0      1      0  53.1000
4           0       3  35.0      0      0   8.0500
..        ...     ...   ...    ...    ...      ...
886         0       2  27.0      0      0  13.0000
887         1       1  19.0      0      0  30.0000
888         0       3   NaN      1      2  23.4500
889         1       1  26.0      0      0  30.0000
890         0       3  32.0      0      0   7.7500

[891 rows x 6 columns]

In [3]:
df['fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: fare, dtype: float64

In [4]:
df['fare category'] = pd.cut(
                            df['fare'], 
                            bins=[0, 10, 20, 30, 40, 50], 
                            labels=['very low', 'low', 'medium', 'high', 'very high']
                            )

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare category
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,very low
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,NaN
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,very low
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,NaN
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,very low

In [6]:
pd.cut(df['fare'], bins=5).value_counts().sort_index()

fare
(-0.512, 102.466]     838
(102.466, 204.932]     33
(204.932, 307.398]     17
(307.398, 409.863]      0
(409.863, 512.329]      3
Name: count, dtype: int64

## Dummy variables

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   survived       891 non-null    int64
 1   pclass         891 non-null    int64
 2   sex            891 non-null    object
 3   age            714 non-null    float64
 4   sibsp          891 non-null    int64
 5   parch          891 non-null    int64
 6   fare           891 non-null    float64
 7   embarked       889 non-null    object
 8   class          891 non-null    category
 9   who            891 non-null    object
 10  adult_male     891 non-null    bool
 11  deck           203 non-null    category
 12  embark_town    889 non-null    object
 13  alive          891 non-null    object
 14  alone          891 non-null    bool
 15  fare category  716 non-null    category
dtypes: bool(2), category(3), float64(2), int64(4), object(5)
memory usage: 81.7+ KB

In [9]:
for i in df.columns:
    print(f"{i}: {df[i].nunique()} unique values")
    print(df[i].value_counts())
    print("\n")

survived: 2 unique values
survived
0    549
1    342
Name: count, dtype: int64


pclass: 3 unique values
pclass
3    491
1    216
2    184
Name: count, dtype: int64


sex: 2 unique values
sex
male      577
female    314
Name: count, dtype: int64


age: 88 unique values
age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64


sibsp: 7 unique values
sibsp
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64


parch: 7 unique values
parch
0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: count, dtype: int64


fare: 248 unique values
fare
8.0500     43
13.0000    42
7.8958     38
7.7500     34
26.0000    31
           ..
13.8583     1
50.4958     1
5.0000      1
9.8458      1
10.5167     1
Name: count, Length: 248, dtype: int64


embarked: 3 unique values
embarked
S    644
C    168
Q     77
Name: count, dtype: int64


class: 3 unique values
class
Third     491
First     216
Second    184
Name: count, dtype: int64


who: 3 unique values
who
man      537
woman    271
child     83
Name: count, dtype: int64


adult_male: 2 unique values
adult_male
True     537
False    354
Name: count, dtype: int64


deck: 7 unique values
deck
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64


embark_town: 3 unique values
embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64


alive: 2 unique values
alive
no     549
yes    342
Name: count, dtype: int64


alone: 2 unique values
alone
True     537
False    354
Name: count, dtype: int64


fare category: 5 unique values
fare category
very low     321
low          179
medium       142
high          58
very high     16
Name: count, dtype: int64

In [11]:
dummy_data  = pd.get_dummies(df)

In [12]:
pd.get_dummies(df, drop_first=True)

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,embarked_Q,...,deck_E,deck_F,deck_G,embark_town_Queenstown,embark_town_Southampton,alive_yes,fare category_low,fare category_medium,fare category_high,fare category_very high
0,0,3,22.0,1,0,7.2500,True,False,True,False,...,False,False,False,False,True,False,False,False,False,False
1,1,1,38.0,1,0,71.2833,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,1,3,26.0,0,0,7.9250,False,True,False,False,...,False,False,False,False,True,True,False,False,False,False
3,1,1,35.0,1,0,53.1000,False,False,False,False,...,False,False,False,False,True,True,False,False,False,False
4,0,3,35.0,0,0,8.0500,True,True,True,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,True,True,True,False,...,False,False,False,False,True,False,True,False,False,False
887,1,1,19.0,0,0,30.0000,False,True,False,False,...,False,False,False,False,True,True,False,True,False,False
888,0,3,NaN,1,2,23.4500,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
889,1,1,26.0,0,0,30.0000,True,True,True,False,...,False,False,False,False,False,True,False,True,False,False
890,0,3,32.0,0,0,7.7500,True,True,True,True,...,False,False,False,True,False,False,False,False,False,False

In [15]:
onehot = sk.preprocessing.OneHotEncoder()

In [18]:
onehot.fit_transform(df)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14256 stored elements and shape (891, 392)>

In [21]:
data = df[['sex', 'embarked']].head()

In [22]:
data_encoded = onehot.fit_transform(data)

In [24]:
pd.DataFrame(data_encoded )

                                                   0
0  <Compressed Sparse Row sparse matrix of dtype ...
1  <Compressed Sparse Row sparse matrix of dtype ...
2  <Compressed Sparse Row sparse matrix of dtype ...
3  <Compressed Sparse Row sparse matrix of dtype ...
4  <Compressed Sparse Row sparse matrix of dtype ...

In [41]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,fare category
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,very low
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,NaN
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,very low
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,NaN
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,very low

In [1]:
import numpy as np
np.log(df.fare)

NameError: name 'df' is not defined

In [2]:
import numpy as np

In [3]:
np.log([4,5,900,1234])

array([1.38629436, 1.60943791, 6.80239476, 7.1180162 ])

In [4]:
import math as m

In [6]:
m.factorial(7)

5040

In [8]:
print(m.floor(8.345))
print(m.ceil(8.345))

8
9